// Generated by gencpp from file custom_msgs/FindObject.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_FINDOBJECT_H
#define CUSTOM_MSGS_MESSAGE_FINDOBJECT_H

#include <ros/service_traits.h>


#include <custom_msgs/FindObjectRequest.h>
#include <custom_msgs/FindObjectResponse.h>


namespace custom_msgs
{

struct FindObject
{

typedef FindObjectRequest Request;
typedef FindObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindObject
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::FindObject > {
  static const char* value()
  {
    return "e662bd1e54b46dd4aec1dcc871579256";
  }

  static const char* value(const ::custom_msgs::FindObject&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::FindObject > {
  static const char* value()
  {
    return "custom_msgs/FindObject";
  }

  static const char* value(const ::custom_msgs::FindObject&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::FindObjectRequest> should match
// service_traits::MD5Sum< ::custom_msgs::FindObject >
template<>
struct MD5Sum< ::custom_msgs::FindObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::FindObject >::value();
  }
  static const char* value(const ::custom_msgs::FindObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::FindObjectRequest> should match
// service_traits::DataType< ::custom_msgs::FindObject >
template<>
struct DataType< ::custom_msgs::FindObjectRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::FindObject >::value();
  }
  static const char* value(const ::custom_msgs::FindObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::FindObjectResponse> should match
// service_traits::MD5Sum< ::custom_msgs::FindObject >
template<>
struct MD5Sum< ::custom_msgs::FindObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::FindObject >::value();
  }
  static const char* value(const ::custom_msgs::FindObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::FindObjectResponse> should match
// service_traits::DataType< ::custom_msgs::FindObject >
template<>
struct DataType< ::custom_msgs::FindObjectResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::FindObject >::value();
  }
  static const char* value(const ::custom_msgs::FindObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_FINDOBJECT_H
