// Generated by gencpp from file custom_msgs/InverseKinematics.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_INVERSEKINEMATICS_H
#define CUSTOM_MSGS_MESSAGE_INVERSEKINEMATICS_H

#include <ros/service_traits.h>


#include <custom_msgs/InverseKinematicsRequest.h>
#include <custom_msgs/InverseKinematicsResponse.h>


namespace custom_msgs
{

struct InverseKinematics
{

typedef InverseKinematicsRequest Request;
typedef InverseKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InverseKinematics
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::InverseKinematics > {
  static const char* value()
  {
    return "64e345b87f38099c3cc1cc7c03cb146a";
  }

  static const char* value(const ::custom_msgs::InverseKinematics&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::InverseKinematics > {
  static const char* value()
  {
    return "custom_msgs/InverseKinematics";
  }

  static const char* value(const ::custom_msgs::InverseKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::InverseKinematicsRequest> should match
// service_traits::MD5Sum< ::custom_msgs::InverseKinematics >
template<>
struct MD5Sum< ::custom_msgs::InverseKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::InverseKinematics >::value();
  }
  static const char* value(const ::custom_msgs::InverseKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::InverseKinematicsRequest> should match
// service_traits::DataType< ::custom_msgs::InverseKinematics >
template<>
struct DataType< ::custom_msgs::InverseKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::InverseKinematics >::value();
  }
  static const char* value(const ::custom_msgs::InverseKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::InverseKinematicsResponse> should match
// service_traits::MD5Sum< ::custom_msgs::InverseKinematics >
template<>
struct MD5Sum< ::custom_msgs::InverseKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::InverseKinematics >::value();
  }
  static const char* value(const ::custom_msgs::InverseKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::InverseKinematicsResponse> should match
// service_traits::DataType< ::custom_msgs::InverseKinematics >
template<>
struct DataType< ::custom_msgs::InverseKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::InverseKinematics >::value();
  }
  static const char* value(const ::custom_msgs::InverseKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_INVERSEKINEMATICS_H
