// Generated by gencpp from file custom_msgs/SmoothPathResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_SMOOTHPATHRESPONSE_H
#define CUSTOM_MSGS_MESSAGE_SMOOTHPATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct SmoothPathResponse_
{
  typedef SmoothPathResponse_<ContainerAllocator> Type;

  SmoothPathResponse_()
    : smooth_path()  {
    }
  SmoothPathResponse_(const ContainerAllocator& _alloc)
    : smooth_path(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _smooth_path_type;
  _smooth_path_type smooth_path;





  typedef boost::shared_ptr< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SmoothPathResponse_

typedef ::custom_msgs::SmoothPathResponse_<std::allocator<void> > SmoothPathResponse;

typedef boost::shared_ptr< ::custom_msgs::SmoothPathResponse > SmoothPathResponsePtr;
typedef boost::shared_ptr< ::custom_msgs::SmoothPathResponse const> SmoothPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::SmoothPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::SmoothPathResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::SmoothPathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.smooth_path == rhs.smooth_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::SmoothPathResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::SmoothPathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0964cb2ce291cfbc90eb48b9d7f07536";
  }

  static const char* value(const ::custom_msgs::SmoothPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0964cb2ce291cfbcULL;
  static const uint64_t static_value2 = 0x90eb48b9d7f07536ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/SmoothPathResponse";
  }

  static const char* value(const ::custom_msgs::SmoothPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/Path smooth_path\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::custom_msgs::SmoothPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.smooth_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SmoothPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::SmoothPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::SmoothPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "smooth_path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.smooth_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_SMOOTHPATHRESPONSE_H
