// Generated by gencpp from file custom_msgs/SmoothPath.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_SMOOTHPATH_H
#define CUSTOM_MSGS_MESSAGE_SMOOTHPATH_H

#include <ros/service_traits.h>


#include <custom_msgs/SmoothPathRequest.h>
#include <custom_msgs/SmoothPathResponse.h>


namespace custom_msgs
{

struct SmoothPath
{

typedef SmoothPathRequest Request;
typedef SmoothPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SmoothPath
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::SmoothPath > {
  static const char* value()
  {
    return "1289371252c92dded0a65b38c8275c64";
  }

  static const char* value(const ::custom_msgs::SmoothPath&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::SmoothPath > {
  static const char* value()
  {
    return "custom_msgs/SmoothPath";
  }

  static const char* value(const ::custom_msgs::SmoothPath&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::SmoothPathRequest> should match
// service_traits::MD5Sum< ::custom_msgs::SmoothPath >
template<>
struct MD5Sum< ::custom_msgs::SmoothPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::SmoothPath >::value();
  }
  static const char* value(const ::custom_msgs::SmoothPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::SmoothPathRequest> should match
// service_traits::DataType< ::custom_msgs::SmoothPath >
template<>
struct DataType< ::custom_msgs::SmoothPathRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::SmoothPath >::value();
  }
  static const char* value(const ::custom_msgs::SmoothPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::SmoothPathResponse> should match
// service_traits::MD5Sum< ::custom_msgs::SmoothPath >
template<>
struct MD5Sum< ::custom_msgs::SmoothPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::SmoothPath >::value();
  }
  static const char* value(const ::custom_msgs::SmoothPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::SmoothPathResponse> should match
// service_traits::DataType< ::custom_msgs::SmoothPath >
template<>
struct DataType< ::custom_msgs::SmoothPathResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::SmoothPath >::value();
  }
  static const char* value(const ::custom_msgs::SmoothPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_SMOOTHPATH_H
