(cl:defpackage custom_msgs-srv
  (:use )
  (:export
   "FINDOBJECT"
   "<FINDOBJECT-REQUEST>"
   "FINDOBJECT-REQUEST"
   "<FINDOBJECT-RESPONSE>"
   "FINDOBJECT-RESPONSE"
   "FORWARDKINEMATICS"
   "<FORWARDKINEMATICS-REQUEST>"
   "FORWARDKINEMATICS-REQUEST"
   "<FORWARDKINEMATICS-RESPONSE>"
   "FORWARDKINEMATICS-RESPONSE"
   "INVERSEKINEMATICS"
   "<INVERSEKINEMATICS-REQUEST>"
   "INVERSEKINEMATICS-REQUEST"
   "<INVERSEKINEMATICS-RESPONSE>"
   "INVERSEKINEMATICS-RESPONSE"
   "SMOOTHPATH"
   "<SMOOTHPATH-REQUEST>"
   "SMOOTHPATH-REQUEST"
   "<SMOOTHPATH-RESPONSE>"
   "SMOOTHPATH-RESPONSE"
  ))

