(cl:defpackage navig_msgs-srv
  (:use )
  (:export
   "GETBOUNDARYPOINTS"
   "<GETBOUNDARYPOINTS-REQUEST>"
   "GETBOUNDARYPOINTS-REQUEST"
   "<GETBOUNDARYPOINTS-RESPONSE>"
   "GETBOUNDARYPOINTS-RESPONSE"
   "GETGOALPOINT"
   "<GETGOALPOINT-REQUEST>"
   "GETGOALPOINT-REQUEST"
   "<GETGOALPOINT-RESPONSE>"
   "GETGOALPOINT-RESPONSE"
   "GETINFLATEDMAP"
   "<GETINFLATEDMAP-REQUEST>"
   "GETINFLATEDMAP-REQUEST"
   "<GETINFLATEDMAP-RESPONSE>"
   "GETINFLATEDMAP-RESPONSE"
  ))

