// Generated by gencpp from file navig_msgs/GetGoalPointResponse.msg
// DO NOT EDIT!


#ifndef NAVIG_MSGS_MESSAGE_GETGOALPOINTRESPONSE_H
#define NAVIG_MSGS_MESSAGE_GETGOALPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace navig_msgs
{
template <class ContainerAllocator>
struct GetGoalPointResponse_
{
  typedef GetGoalPointResponse_<ContainerAllocator> Type;

  GetGoalPointResponse_()
    : goal()  {
    }
  GetGoalPointResponse_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetGoalPointResponse_

typedef ::navig_msgs::GetGoalPointResponse_<std::allocator<void> > GetGoalPointResponse;

typedef boost::shared_ptr< ::navig_msgs::GetGoalPointResponse > GetGoalPointResponsePtr;
typedef boost::shared_ptr< ::navig_msgs::GetGoalPointResponse const> GetGoalPointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navig_msgs::GetGoalPointResponse_<ContainerAllocator1> & lhs, const ::navig_msgs::GetGoalPointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navig_msgs::GetGoalPointResponse_<ContainerAllocator1> & lhs, const ::navig_msgs::GetGoalPointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navig_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ad3bd0e46ff6777ce7cd2fdd945cb9e";
  }

  static const char* value(const ::navig_msgs::GetGoalPointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ad3bd0e46ff6777ULL;
  static const uint64_t static_value2 = 0xce7cd2fdd945cb9eULL;
};

template<class ContainerAllocator>
struct DataType< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navig_msgs/GetGoalPointResponse";
  }

  static const char* value(const ::navig_msgs::GetGoalPointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"geometry_msgs/Point goal\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::navig_msgs::GetGoalPointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGoalPointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navig_msgs::GetGoalPointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navig_msgs::GetGoalPointResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIG_MSGS_MESSAGE_GETGOALPOINTRESPONSE_H
