// Generated by gencpp from file navig_msgs/GetGoalPointRequest.msg
// DO NOT EDIT!


#ifndef NAVIG_MSGS_MESSAGE_GETGOALPOINTREQUEST_H
#define NAVIG_MSGS_MESSAGE_GETGOALPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace navig_msgs
{
template <class ContainerAllocator>
struct GetGoalPointRequest_
{
  typedef GetGoalPointRequest_<ContainerAllocator> Type;

  GetGoalPointRequest_()
    : pos_x_robot(0.0)
    , pos_y_robot(0.0)
    , pos_a_robot(0.0)
    , points()
    , last_objective()
    , method()  {
    }
  GetGoalPointRequest_(const ContainerAllocator& _alloc)
    : pos_x_robot(0.0)
    , pos_y_robot(0.0)
    , pos_a_robot(0.0)
    , points(_alloc)
    , last_objective(_alloc)
    , method(_alloc)  {
  (void)_alloc;
    }



   typedef float _pos_x_robot_type;
  _pos_x_robot_type pos_x_robot;

   typedef float _pos_y_robot_type;
  _pos_y_robot_type pos_y_robot;

   typedef float _pos_a_robot_type;
  _pos_a_robot_type pos_a_robot;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _last_objective_type;
  _last_objective_type last_objective;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _method_type;
  _method_type method;





  typedef boost::shared_ptr< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGoalPointRequest_

typedef ::navig_msgs::GetGoalPointRequest_<std::allocator<void> > GetGoalPointRequest;

typedef boost::shared_ptr< ::navig_msgs::GetGoalPointRequest > GetGoalPointRequestPtr;
typedef boost::shared_ptr< ::navig_msgs::GetGoalPointRequest const> GetGoalPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navig_msgs::GetGoalPointRequest_<ContainerAllocator1> & lhs, const ::navig_msgs::GetGoalPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pos_x_robot == rhs.pos_x_robot &&
    lhs.pos_y_robot == rhs.pos_y_robot &&
    lhs.pos_a_robot == rhs.pos_a_robot &&
    lhs.points == rhs.points &&
    lhs.last_objective == rhs.last_objective &&
    lhs.method == rhs.method;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navig_msgs::GetGoalPointRequest_<ContainerAllocator1> & lhs, const ::navig_msgs::GetGoalPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navig_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be26d578b2f257bf2649cb51b41fcac4";
  }

  static const char* value(const ::navig_msgs::GetGoalPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe26d578b2f257bfULL;
  static const uint64_t static_value2 = 0x2649cb51b41fcac4ULL;
};

template<class ContainerAllocator>
struct DataType< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navig_msgs/GetGoalPointRequest";
  }

  static const char* value(const ::navig_msgs::GetGoalPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_x_robot\n"
"float32 pos_y_robot\n"
"float32 pos_a_robot\n"
"geometry_msgs/Point[] points\n"
"geometry_msgs/Point last_objective\n"
"string method\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::navig_msgs::GetGoalPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x_robot);
      stream.next(m.pos_y_robot);
      stream.next(m.pos_a_robot);
      stream.next(m.points);
      stream.next(m.last_objective);
      stream.next(m.method);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGoalPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navig_msgs::GetGoalPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navig_msgs::GetGoalPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "pos_x_robot: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x_robot);
    s << indent << "pos_y_robot: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y_robot);
    s << indent << "pos_a_robot: ";
    Printer<float>::stream(s, indent + "  ", v.pos_a_robot);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "last_objective: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.last_objective);
    s << indent << "method: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.method);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIG_MSGS_MESSAGE_GETGOALPOINTREQUEST_H
