// Generated by gencpp from file navig_msgs/GetGoalPoint.msg
// DO NOT EDIT!


#ifndef NAVIG_MSGS_MESSAGE_GETGOALPOINT_H
#define NAVIG_MSGS_MESSAGE_GETGOALPOINT_H

#include <ros/service_traits.h>


#include <navig_msgs/GetGoalPointRequest.h>
#include <navig_msgs/GetGoalPointResponse.h>


namespace navig_msgs
{

struct GetGoalPoint
{

typedef GetGoalPointRequest Request;
typedef GetGoalPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGoalPoint
} // namespace navig_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navig_msgs::GetGoalPoint > {
  static const char* value()
  {
    return "3113fe99463fffd3cbc7bac1e2ddceeb";
  }

  static const char* value(const ::navig_msgs::GetGoalPoint&) { return value(); }
};

template<>
struct DataType< ::navig_msgs::GetGoalPoint > {
  static const char* value()
  {
    return "navig_msgs/GetGoalPoint";
  }

  static const char* value(const ::navig_msgs::GetGoalPoint&) { return value(); }
};


// service_traits::MD5Sum< ::navig_msgs::GetGoalPointRequest> should match
// service_traits::MD5Sum< ::navig_msgs::GetGoalPoint >
template<>
struct MD5Sum< ::navig_msgs::GetGoalPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navig_msgs::GetGoalPoint >::value();
  }
  static const char* value(const ::navig_msgs::GetGoalPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navig_msgs::GetGoalPointRequest> should match
// service_traits::DataType< ::navig_msgs::GetGoalPoint >
template<>
struct DataType< ::navig_msgs::GetGoalPointRequest>
{
  static const char* value()
  {
    return DataType< ::navig_msgs::GetGoalPoint >::value();
  }
  static const char* value(const ::navig_msgs::GetGoalPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navig_msgs::GetGoalPointResponse> should match
// service_traits::MD5Sum< ::navig_msgs::GetGoalPoint >
template<>
struct MD5Sum< ::navig_msgs::GetGoalPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navig_msgs::GetGoalPoint >::value();
  }
  static const char* value(const ::navig_msgs::GetGoalPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navig_msgs::GetGoalPointResponse> should match
// service_traits::DataType< ::navig_msgs::GetGoalPoint >
template<>
struct DataType< ::navig_msgs::GetGoalPointResponse>
{
  static const char* value()
  {
    return DataType< ::navig_msgs::GetGoalPoint >::value();
  }
  static const char* value(const ::navig_msgs::GetGoalPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIG_MSGS_MESSAGE_GETGOALPOINT_H
