// Generated by gencpp from file navig_msgs/GetInflatedMap.msg
// DO NOT EDIT!


#ifndef NAVIG_MSGS_MESSAGE_GETINFLATEDMAP_H
#define NAVIG_MSGS_MESSAGE_GETINFLATEDMAP_H

#include <ros/service_traits.h>


#include <navig_msgs/GetInflatedMapRequest.h>
#include <navig_msgs/GetInflatedMapResponse.h>


namespace navig_msgs
{

struct GetInflatedMap
{

typedef GetInflatedMapRequest Request;
typedef GetInflatedMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInflatedMap
} // namespace navig_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navig_msgs::GetInflatedMap > {
  static const char* value()
  {
    return "1076cd1faad58325fe5420c98658ec61";
  }

  static const char* value(const ::navig_msgs::GetInflatedMap&) { return value(); }
};

template<>
struct DataType< ::navig_msgs::GetInflatedMap > {
  static const char* value()
  {
    return "navig_msgs/GetInflatedMap";
  }

  static const char* value(const ::navig_msgs::GetInflatedMap&) { return value(); }
};


// service_traits::MD5Sum< ::navig_msgs::GetInflatedMapRequest> should match
// service_traits::MD5Sum< ::navig_msgs::GetInflatedMap >
template<>
struct MD5Sum< ::navig_msgs::GetInflatedMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navig_msgs::GetInflatedMap >::value();
  }
  static const char* value(const ::navig_msgs::GetInflatedMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navig_msgs::GetInflatedMapRequest> should match
// service_traits::DataType< ::navig_msgs::GetInflatedMap >
template<>
struct DataType< ::navig_msgs::GetInflatedMapRequest>
{
  static const char* value()
  {
    return DataType< ::navig_msgs::GetInflatedMap >::value();
  }
  static const char* value(const ::navig_msgs::GetInflatedMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navig_msgs::GetInflatedMapResponse> should match
// service_traits::MD5Sum< ::navig_msgs::GetInflatedMap >
template<>
struct MD5Sum< ::navig_msgs::GetInflatedMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navig_msgs::GetInflatedMap >::value();
  }
  static const char* value(const ::navig_msgs::GetInflatedMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navig_msgs::GetInflatedMapResponse> should match
// service_traits::DataType< ::navig_msgs::GetInflatedMap >
template<>
struct DataType< ::navig_msgs::GetInflatedMapResponse>
{
  static const char* value()
  {
    return DataType< ::navig_msgs::GetInflatedMap >::value();
  }
  static const char* value(const ::navig_msgs::GetInflatedMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIG_MSGS_MESSAGE_GETINFLATEDMAP_H
