// Generated by gencpp from file navig_msgs/GetInflatedMapRequest.msg
// DO NOT EDIT!


#ifndef NAVIG_MSGS_MESSAGE_GETINFLATEDMAPREQUEST_H
#define NAVIG_MSGS_MESSAGE_GETINFLATEDMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/OccupancyGrid.h>

namespace navig_msgs
{
template <class ContainerAllocator>
struct GetInflatedMapRequest_
{
  typedef GetInflatedMapRequest_<ContainerAllocator> Type;

  GetInflatedMapRequest_()
    : inflated_cells(0.0)
    , map()  {
    }
  GetInflatedMapRequest_(const ContainerAllocator& _alloc)
    : inflated_cells(0.0)
    , map(_alloc)  {
  (void)_alloc;
    }



   typedef float _inflated_cells_type;
  _inflated_cells_type inflated_cells;

   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _map_type;
  _map_type map;





  typedef boost::shared_ptr< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetInflatedMapRequest_

typedef ::navig_msgs::GetInflatedMapRequest_<std::allocator<void> > GetInflatedMapRequest;

typedef boost::shared_ptr< ::navig_msgs::GetInflatedMapRequest > GetInflatedMapRequestPtr;
typedef boost::shared_ptr< ::navig_msgs::GetInflatedMapRequest const> GetInflatedMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator1> & lhs, const ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.inflated_cells == rhs.inflated_cells &&
    lhs.map == rhs.map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator1> & lhs, const ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navig_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb1e60991093203f9cc3a6787d5d00b4";
  }

  static const char* value(const ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb1e60991093203fULL;
  static const uint64_t static_value2 = 0x9cc3a6787d5d00b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navig_msgs/GetInflatedMapRequest";
  }

  static const char* value(const ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 inflated_cells\n"
"nav_msgs/OccupancyGrid map\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/OccupancyGrid\n"
"# This represents a 2-D grid map, in which each cell represents the probability of\n"
"# occupancy.\n"
"\n"
"Header header \n"
"\n"
"#MetaData for the map\n"
"MapMetaData info\n"
"\n"
"# The map data, in row-major order, starting with (0,0).  Occupancy\n"
"# probabilities are in the range [0,100].  Unknown is -1.\n"
"int8[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inflated_cells);
      stream.next(m.map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInflatedMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navig_msgs::GetInflatedMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "inflated_cells: ";
    Printer<float>::stream(s, indent + "  ", v.inflated_cells);
    s << indent << "map: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIG_MSGS_MESSAGE_GETINFLATEDMAPREQUEST_H
